import os
from pathlib import Path

def update_components_props(base_path: str):
    base = Path(base_path)
    
    files = {
        "src/components/dashboard/WelcomeHeader.tsx": """import { Target } from 'lucide-react';

export default function WelcomeHeader({ name, goal, progress }: { name: string, goal: string, progress: number }) {
  return (
    <div className="bg-neutral-950 rounded-2xl p-6 sm:p-8 border border-neutral-800 shadow-sm flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
      <div>
        <h1 className="text-2xl sm:text-3xl font-bold text-white mb-2">Good morning, {name} 👋</h1>
        <p className="text-neutral-400">Let's continue building your career.</p>
      </div>

      <div className="w-full md:w-auto bg-neutral-900 p-4 rounded-xl border border-neutral-800 flex items-center gap-4">
        <div className="w-12 h-12 bg-neutral-950 rounded-lg shadow-sm border border-neutral-800 flex items-center justify-center flex-shrink-0">
          <Target className="text-emerald-500" size={24} />
        </div>
        <div className="flex-1">
          <div className="flex justify-between items-end mb-1.5">
            <div>
              <p className="text-xs font-semibold text-emerald-500 uppercase tracking-wide mb-0.5">Your GURI</p>
              <p className="text-white font-bold leading-tight">{goal}</p>
            </div>
            <span className="text-sm font-semibold text-white">{progress}%</span>
          </div>
          <div className="w-48 h-2 bg-neutral-800 rounded-full overflow-hidden">
            <div className="h-full bg-emerald-500 rounded-full" style={{ width: \`\${progress}%\` }}></div>
          </div>
        </div>
      </div>
    </div>
  );
}
""",
        "src/components/dashboard/ContinueLearning.tsx": """import { Play } from 'lucide-react';

export default function ContinueLearning({ learning }: { learning?: any }) {
  if (!learning) return null;
  return (
    <section>
      <h2 className="text-lg font-bold text-white mb-4">Continue Learning</h2>
      
      <div className="bg-neutral-950 rounded-2xl border border-neutral-800 shadow-sm p-6 group hover:border-emerald-500/50 transition-colors">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6">
          <div className="flex-1">
            <div className="text-sm font-medium text-emerald-400 mb-2">Next up</div>
            <h3 className="text-xl font-bold text-white mb-2">{learning.title}</h3>
            
            <div className="flex items-center gap-4 text-sm font-medium mt-4">
              <div className="flex items-center gap-2 flex-1 max-w-[200px]">
                <span className="text-neutral-300">Progress</span>
                <div className="flex-1 h-1.5 bg-neutral-800 rounded-full overflow-hidden">
                  <div className="h-full bg-emerald-500" style={{width: \`\${learning.progress}%\`}}></div>
                </div>
                <span className="text-white">{learning.progress}%</span>
              </div>
            </div>
          </div>
          
          <button className="w-full sm:w-auto bg-white text-black px-6 py-3 rounded-xl font-medium hover:bg-neutral-200 transition-colors flex items-center justify-center gap-2">
            Continue <Play size={16} className="fill-current" />
          </button>
        </div>
      </div>
    </section>
  );
}
""",
        "src/components/dashboard/TodayPlan.tsx": """import { CheckCircle2, Circle, PlayCircle } from 'lucide-react';
import { cn } from '@/lib/utils';

export default function TodayPlan({ plan }: { plan?: any[] }) {
  const planItems = plan || [];
  if (planItems.length === 0) return null;

  return (
    <section>
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-bold text-white">Today's Learning Plan</h2>
        <span className="text-xs font-medium text-emerald-400 bg-emerald-500/10 px-2.5 py-1 rounded-full">Generated by AI</span>
      </div>
      
      <div className="bg-neutral-950 rounded-2xl border border-neutral-800 shadow-sm overflow-hidden">
        {planItems.map((item, index) => (
          <div key={index} className={cn(
            "flex items-center justify-between p-4 sm:p-5 transition-colors",
            index !== planItems.length - 1 && "border-b border-neutral-800/50",
            item.status === 'current' ? "bg-emerald-500/5" : "hover:bg-neutral-900"
          )}>
            <div className="flex items-center gap-3 sm:gap-4">
              {item.status === 'done' && <CheckCircle2 className="text-emerald-500 flex-shrink-0" size={20} />}
              {item.status === 'current' && <PlayCircle className="text-emerald-400 flex-shrink-0" size={20} />}
              {item.status === 'pending' && <Circle className="text-neutral-600 flex-shrink-0" size={20} />}
              
              <span className={cn(
                "text-sm sm:text-base font-medium",
                item.status === 'done' ? "text-neutral-500 line-through decoration-neutral-600" : 
                item.status === 'current' ? "text-emerald-300" : "text-neutral-300"
              )}>
                {item.title}
              </span>
            </div>
            
            <div className="flex items-center gap-4">
              <span className="text-xs sm:text-sm font-medium text-neutral-500">{item.duration}</span>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
""",
        "src/components/dashboard/SkillProgress.tsx": """export default function SkillProgress({ skills }: { skills?: any[] }) {
  const skillsList = skills || [];
  if (skillsList.length === 0) return null;
  return (
    <section>
      <h2 className="text-lg font-bold text-white mb-4">Your Skills</h2>
      
      <div className="bg-neutral-950 rounded-2xl border border-neutral-800 shadow-sm p-6 space-y-5">
        {skillsList.map(skill => (
          <div key={skill.name}>
            <div className="flex justify-between items-end mb-2">
              <span className="text-sm font-medium text-neutral-300">{skill.name}</span>
              <span className="text-xs font-bold text-neutral-500">{skill.progress}%</span>
            </div>
            <div className="w-full h-2 bg-neutral-900 rounded-full overflow-hidden">
              <div className="h-full bg-white rounded-full" style={{ width: \`\${skill.progress}%\` }}></div>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
""",
        "src/components/dashboard/ProjectCard.tsx": """import { Code2, ArrowRight } from 'lucide-react';

export default function ProjectCard({ projects }: { projects?: any[] }) {
  if (!projects || projects.length === 0) return null;
  const project = projects[0];

  return (
    <section>
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-bold text-white">Build Something</h2>
      </div>
      
      <div className="bg-neutral-950 rounded-2xl border border-neutral-800 shadow-sm p-6 group cursor-pointer hover:border-neutral-700 transition-colors">
        <div className="w-10 h-10 bg-neutral-900 rounded-lg flex items-center justify-center mb-4">
          <Code2 className="text-neutral-400" size={20} />
        </div>
        
        <h3 className="text-lg font-bold text-white mb-2">{project.title}</h3>
        
        <div className="flex items-center justify-between pt-4 border-t border-neutral-800 mt-4">
          <div className="flex items-center gap-2">
            <span className="text-xs font-medium text-neutral-400">Difficulty: {project.difficulty}</span>
          </div>
          <button className="text-sm font-bold text-white flex items-center gap-1 group-hover:text-emerald-400 transition-colors">
            Start Project <ArrowRight size={16} />
          </button>
        </div>
      </div>
    </section>
  );
}
""",
        "src/components/dashboard/AICoachCard.tsx": """import { Sparkles } from 'lucide-react';

export default function AICoachCard({ recommendation }: { recommendation?: any }) {
  if (!recommendation) return null;
  return (
    <section>
      <h2 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
        Your AI Learning Coach
        <Sparkles size={16} className="text-emerald-400" />
      </h2>
      
      <div className="bg-neutral-900 rounded-2xl border border-neutral-800 shadow-xl p-6 text-white relative overflow-hidden">
        <div className="absolute -top-24 -right-24 w-48 h-48 bg-emerald-500/20 rounded-full blur-[60px]"></div>
        
        <div className="relative z-10">
          <p className="text-neutral-400 text-sm mb-4">
            {recommendation.reason}
          </p>
          
          <div className="bg-black/40 backdrop-blur-md rounded-xl p-4 border border-white/5 mb-6">
            <div className="text-xs font-semibold text-emerald-400 uppercase tracking-wide mb-1">Next Recommended Step</div>
            <h3 className="text-lg font-bold text-white mb-2">{recommendation.title}</h3>
          </div>

          <button className="w-full bg-emerald-500 text-black font-semibold py-3 rounded-xl hover:bg-emerald-400 transition-colors flex items-center justify-center shadow-lg">
            Ask AI Coach <span className="ml-2">→</span>
          </button>
        </div>
      </div>
    </section>
  );
}
""",
        "src/components/dashboard/RoadmapProgress.tsx": """import { CheckCircle2, Circle } from 'lucide-react';
import { cn } from '@/lib/utils';

export default function RoadmapProgress({ roadmap }: { roadmap?: any }) {
  if (!roadmap) return null;
  return (
    <section>
      <h2 className="text-lg font-bold text-white mb-4">Your Roadmap</h2>
      
      <div className="bg-neutral-950 rounded-2xl border border-neutral-800 shadow-sm p-6">
        <div className="text-xs font-semibold text-emerald-400 uppercase tracking-wide mb-1">{roadmap.title}</div>
        
        <div className="mt-4 flex items-center gap-4">
          <span className="text-neutral-300">Overall Progress</span>
          <div className="flex-1 h-1.5 bg-neutral-800 rounded-full overflow-hidden">
            <div className="h-full bg-emerald-500" style={{width: \`\${roadmap.progress}%\`}}></div>
          </div>
          <span className="text-white">{roadmap.progress}%</span>
        </div>

        <button className="w-full mt-6 py-2.5 rounded-lg border border-neutral-800 text-sm font-semibold text-neutral-300 hover:bg-neutral-900 transition-colors">
          View Full Roadmap →
        </button>
      </div>
    </section>
  );
}
"""
    }
    
    for filepath, content in files.items():
        with open(base / filepath, "w", encoding="utf-8") as f:
            f.write(content.replace("\\`", "`"))
            
    print("Dashboard components updated to use props")

if __name__ == "__main__":
    update_components_props("d:/GURI")
