import { CheckCircle2, Circle, PlayCircle } from 'lucide-react';
import { cn } from '@/lib/utils';

export default function TodayPlan({ plan }: { plan?: any[] }) {
  const planItems = plan || [];
  if (planItems.length === 0) return null;

  return (
    <section>
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-bold text-white">Today's Learning Plan</h2>
        <span className="text-xs font-medium text-emerald-400 bg-emerald-500/10 px-2.5 py-1 rounded-full">Generated by AI</span>
      </div>
      
      <div className="bg-neutral-950 rounded-2xl border border-neutral-800 shadow-sm overflow-hidden">
        {planItems.map((item, index) => (
          <div key={index} className={cn(
            "flex items-center justify-between p-4 sm:p-5 transition-colors",
            index !== planItems.length - 1 && "border-b border-neutral-800/50",
            item.status === 'current' ? "bg-emerald-500/5" : "hover:bg-neutral-900"
          )}>
            <div className="flex items-center gap-3 sm:gap-4">
              {item.status === 'done' && <CheckCircle2 className="text-emerald-500 flex-shrink-0" size={20} />}
              {item.status === 'current' && <PlayCircle className="text-emerald-400 flex-shrink-0" size={20} />}
              {item.status === 'pending' && <Circle className="text-neutral-600 flex-shrink-0" size={20} />}
              
              <span className={cn(
                "text-sm sm:text-base font-medium",
                item.status === 'done' ? "text-neutral-500 line-through decoration-neutral-600" : 
                item.status === 'current' ? "text-emerald-300" : "text-neutral-300"
              )}>
                {item.title}
              </span>
            </div>
            
            <div className="flex items-center gap-4">
              <span className="text-xs sm:text-sm font-medium text-neutral-500">{item.duration}</span>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
